name: Compile

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Compile with Deno
        run: deno run -A _build.ts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/clank-x86_64-unknown-linux-gnu
            build/clank-aarch64-apple-darwin 
            build/clank-x86_64-apple-darwin
            build/clank-x86_64-pc-windows-msvc.exe
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
